name: kthcloud-ci
"on":
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: robot$deploy-c819e8dc-11fe-4c30-b2d5-9f4acfe86aa0+message-microservice
          password: c9hH9N3NRn452BnbTIGngo3wcNd9aQh9
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: registry.cloud.cbh.kth.se/deploy-c819e8dc-11fe-4c30-b2d5-9f4acfe86aa0/message-microservice